name: Deploying to Live

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.MAIN_SERVER_IP }}
          port: 21
          server-dir: wp-content/themes/nbc/
          username: ${{ secrets.MAIN_FTP_USERNAME }}
          password: ${{ secrets.MAIN_FTP_PASSWORD }}
          # Requires secrets to be added to the repo (Settings > Secrets)
